Create Pyhton
  File "<stdin>", line 1
    print s
    ^
IndentationError: unexpected indent
>>>           ^
  File "<stdin>", line 1
    ^
    ^
IndentationError: unexpected indent
>>> SyntaxError: Missing parentheses in call to 'print'. Did you mean print(s)?
  File "<stdin>", line 1
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print(s)?
                         ^
SyntaxError: invalid syntax
>>> >>> s= 'first line.\nsecond line.'
  File "<stdin>", line 1
    >>> s= 'first line.\nsecond line.'
    ^
SyntaxError: invalid syntax
>>> >>> print s
  File "<stdin>", line 1
    >>> print s
    ^
SyntaxError: invalid syntax
>>>   File "<stdin>", line 1
  File "<stdin>", line 1
    File "<stdin>", line 1
    ^
IndentationError: unexpected indent
>>>     print s
  File "<stdin>", line 1
    print s
    ^
IndentationError: unexpected indent
>>>           ^
  File "<stdin>", line 1
    ^
    ^
IndentationError: unexpected indent
>>> SyntaxError: Missing parentheses in call to 'print'. Did you mean print(s)?
  File "<stdin>", line 1
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print(s)?
                         ^
SyntaxError: invalid syntax
>>> >>> s= first line.nSecond line.'
  File "<stdin>", line 1
    >>> s= first line.nSecond line.'
    ^
SyntaxError: invalid syntax
>>>   File "<stdin>", line 1
  File "<stdin>", line 1
    File "<stdin>", line 1
    ^
IndentationError: unexpected indent
>>>     s= first line.nSecond line.'
  File "<stdin>", line 1
    s= first line.nSecond line.'
    ^
IndentationError: unexpected indent
>>>              ^
  File "<stdin>", line 1
    ^
    ^
IndentationError: unexpected indent
>>> SyntaxError: invalid syntax
  File "<stdin>", line 1
    SyntaxError: invalid syntax
                         ^
SyntaxError: invalid syntax
>>> >>> s= 'First lin.\nSecond line.'
  File "<stdin>", line 1
    >>> s= 'First lin.\nSecond line.'
    ^
SyntaxError: invalid syntax
>>> >>> print s
  File "<stdin>", line 1
    >>> print s
    ^
SyntaxError: invalid syntax
>>>   File "<stdin>", line 1
  File "<stdin>", line 1
    File "<stdin>", line 1
    ^
IndentationError: unexpected indent
>>>     print s
  File "<stdin>", line 1
    print s
    ^
IndentationError: unexpected indent
>>>           ^
  File "<stdin>", line 1
    ^
    ^
IndentationError: unexpected indent
>>> SyntaxError: Missing parentheses in call to 'print'. Did you mean print(s)?
  File "<stdin>", line 1
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print(s)?
                         ^
SyntaxError: invalid syntax
>>> >>>